### ISSUE TITLE
Suppress tab staff

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#13]
Hello,
Is there any way for a track to display a music staff without a tab staff? This would be useful for example on vocal tracks.

Thanks for creating tabr. I'm really enjoying it so far.

**Comment by leonawicz** [comment]
There is now! 😃 Thanks for the great suggestion. I've added a `no_tab` argument to `track`, which is carried along until you call `tab` or `lilypond`. Those functions will exclude the LilyPond syntax for the tab staff in the rendered output for any individual track that had `no_tab = TRUE`. (Just can't make a `track` with both `music_taff = NA` and `no_tab = TRUE` obviously; that will return an error message.)

I've updated the docs as well. I also made some other unrelated changes in the latest update. I tested this new feature with a few examples and the output looked good. Please test with the dev version here on GitHub and let me know if you encounter any problems, but it should be good now. I plan to do a CRAN update soon folding in my other changes as well so please let me know this worked for you.

**Comment by kimo-k** [comment]
Thanks for the timely action. Everything works for me.
