### ISSUE TITLE
Request: support "s" as invisible rest in notes

### ISSUE THREAD

**Issue by HanOostdijk** [leonawicz/tabr#30]
Currently `'s'` is not supported in notes in `tabr`. However it is in Lilypond for invisible rests.
Hereby the request to allow this in notes.

(related to comment in [issue #29](https://github.com/leonawicz/tabr/issues/29) )

Regards Han

**Comment by leonawicz** [comment]
This feature has existed since day one. Perhaps I broke it in a recent commit? I will look into this, thanks.

**Comment by leonawicz** [comment]
Perhaps I am misunderstanding. Do these not insert invisible rests for you?

```
phrase("s1 s2 c s4 c2. s8 c2..") %>% 
  track() %>% score() %>% render_tab("out.pdf")
phrase("s s c s c s c", "1 2 2 4 2. 8 2..") %>% 
  track() %>% score() %>% render_tab("out2.pdf")
```

Both are equivalent specifications and should produce the same output. I get valid LilyPond output and the pdf outputs contain the invisible rests.

**Comment by HanOostdijk** [comment]
Shame, shame:
This was caused by a `tabraux` function that did not support the 's' 
Sorry for the inconvenience caused.
I will close this as soon as possible ;)

Regards Han
