### ISSUE TITLE
Mystery of the missing 7th scale degree

### ISSUE THREAD

**Issue by JDK19612** [leonawicz/tabr#32]
```
> scale_note(1:8,key="e",scale="major")
<Noteworthy string>
  Format: vectorized time
  Values: e f# g# a b c# e
> scale_note(1:9,key="e",scale="major")
<Noteworthy string>
  Format: vectorized time
  Values: e f# g# a b c# e f#
```

I can't help but wonder what happened to the 7th scale degree (D#).

```
> scale_note(1:9,key="c",scale="major")
<Noteworthy string>
  Format: vectorized time
  Values: c d e f g a c d
```

Same issue here. I would expect a "b".

This occurred in R 3.6.2 (x64), installed today, along with tabr and its dependencies.

**Comment by leonawicz** [comment]
Thanks! This is fixed now on GitHub. I was using modulus to recycle the note indices. E.g., `1:8` becomes `c(1, 2, 3, 4, 5, 6, 0, 1)`. I forgot to set any zeros back to length of scale. Easy fix.
