### ISSUE TITLE
using a list in trackbind()

### ISSUE THREAD

**Issue by ratnanil** [leonawicz/tabr#33]
For technical reasons, I have all my tracks in a list (`x_list`). Is there a way to use trackbind() on a `list` of tracks? I'd be happy to use purrr or the like, I just haven't found a way to implement this yet.

``` r
library(tabr)
x <- phrase("c ec'g' ec'g'", "4 4 2", "5 432 432")
x1 <- track(x)
x2 <- track(x, voice = 2)
x_list <- list(x1,x2)
trackbind(x_list)
#> Error: All arguments must be `track` tables.
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ratnanil** [comment]
oh my bad..  this does the trick:

```do.call(trackbind,x_list)```

**Comment by leonawicz** [comment]
@ratnanil Hey, thanks for your question. Yeah I was just going to suggest do.call(). It's the general solution for exactly this kind of issue. Glad this works for you!
