### ISSUE TITLE
Tuning render error

### ISSUE THREAD

**Issue by fnord-repeater** [leonawicz/tabr#37]
When I use a tuning with a lot of sharps, the tuning on my score pdf gets messed up. It looks like a horizontal list of F CIS A FIS B...

```library(tabr)
tuning <- "f#,b,f#ac#'f#'"
track(p('c4 d e'),tuning=tuning)  %>% score %>% lilypond('test.ly', key="a")
```
The compiled lilypond looks like this - some issues with quotes, I guess:
```
\set TabStaff.instrumentName = \markup  { \hspace #7 \override #'(baseline-skip . 1.5)  \column \fontsize #-4.5 \sans { F#" CIS A FIS B "FIS } }
```

**Comment by leonawicz** [comment]
Fixed on GitHub. Thanks!
