### ISSUE TITLE
Integrating tabr output into greater lilypond score

### ISSUE THREAD

**Issue by kimo-k** [leonawicz/tabr#38]
Hello,

I'd like your input on how to integrate output from tabr into a greater lilypond score. 

I can't simply include the .ly file in another, because it will render itself when it is included.

Maybe you could add an argument to `lilypond`, or a separate function, which only generates the staves without calling `\score` or defining the header. These staves could have variable names based on the r source file name, so the output of multiple tabr projects could be combined. 

Or is there a better solution?

It would also be nice to be able to include lilypond files and code in the r source, although I'm not sure exactly how that would work.

**Comment by leonawicz** [comment]
I'm not sure I can effectively help with this. The individual pieces within the output of `lilypond()` are very contextual in how they are combined into a complete file. I don't want to add arguments or new functions that write out partial components of a file in an attempt to predict how users would prefer those individual pieces be structured to fit their unique broader project. That's beyond the scope of tabr, and rather impossible to satisfy for users in general.

I'm wondering though, what specifically are you attempting to do? If you are making one score, I'm not sure why you would create multiple score objects across multiple R projects. If I understand correctly, it would make more sense to make one score in R, not turn it into one score afterward in LilyPond. I'm wondering if this is more of a project organization/workflow problem. I need more context or a small specific example to understand clearly.

Can you clarify regarding the "lilypond files and code in r source"? The package contains examples of R code that generate LilyPond files.

**Comment by leonawicz** [comment]
I'd like to have more types of LilyPond content for tabr to export, but it's hard to say what this would or should look like and there isn't sufficient demand for it. I ended up taking more interest in the "sheet music snippets" that can be created from music objects and are great additions for Rmarkdown rendered documents and that received much more user feedback.
