### ISSUE TITLE
plot 5 string instrument

### ISSUE THREAD

**Issue by franciscotovarmit** [leonawicz/tabr#40]
hi thanks for your code it is great!

I would like to create chord diagrams for a guitar that has 5 strings. I have not been able to modify your example with success
I have only removed the 6th string on the chord diagram. 
How can I tell to plot_chord() that this is a 5 string instrument?

chords <- c("02210", 
            "32010", 
            "00232", 
            "33211", 
            "22100")
id <- c("Am", "C", "D", "F", "E")

g <- map2(chords, id, ~{
  plot_chord(.x, "notes", point_size = 8, fret_range = c(0, 4), accidentals = "sharp", asp = 1.25) + 
    ggtitle(.y)
})

grid.arrange(grobs = g, nrow = 2)

**Comment by leonawicz** [comment]
Thanks. Please see the function documentation and the `tuning` argument.

```
plot_chord("02210", "Am", tuning = "standard", show_tuning = TRUE)
```

Even though you're electing not to display the tuning, it's a relevant and fundamental component of the function. As a result, the number of strings is simply derived from it. If you're not displaying it, you can even put in a fake one like `"aaaaa"` to imply a 5-string instrument.

Best regards
