### ISSUE TITLE
Can plot_fretboard print "dot" fret numbers? (3, 5, 7, etc)

### ISSUE THREAD

**Issue by AHMcKenzie** [leonawicz/tabr#41]
Hello, 

Thanks for putting together this package, I'm using it to print practice scales for guitar, specifically the "plot_fretboard" function. I wanted to ask if there's a way to get this function to flag frets # 3, 5, 7, 9, 12, as would be on a regular guitar, for ease of use. Presently the function only prints the lowest fret number when it is non-zero.

I unsuccesfully tried to make a copy of the function to see if I could debug and pin-point the lines where fret numbers are printed. There are several function dependencies that seem to get broken using that approach.

Thanks,
Alex

**Comment by leonawicz** [comment]
Completed in version 0.5.0.

**Comment by AHMcKenzie** [comment]
Hey Matt,
Thanks for the update. I updated the package and tried the new "fret_label"
parameter but I'm getting this error message:

*Error: Explicit fret range will cut off notes.*

I'm using the "fret_range" clause on my scripts, they worked well before.
When used with your sample plot_fretboard() call, I get the same error.
This is the test line:

plot_fretboard <https://leonawicz.github.io/tabr/reference/plot_fretboard.html>(string,
fret, "notes", show_tuning = TRUE, fret_labels = c
<https://rdrr.io/r/base/c.html>(3, 5, 7, 9, 12), fret_range = c(4,
10))

Please advice, thanks,
Alex
