### ISSUE TITLE
How to play the guitar in R?

### ISSUE THREAD

**Issue by YanglabWCH** [leonawicz/tabr#7]
Hello leonawicz,

So cool package you have done. One question about tabr, could we play the guitar tablature in tabr after producing it ?

Thanks a lot~~

Shisheng

**Comment by leonawicz** [comment]
Thank you for your feedback. The `tab` function will use LilyPond to render the code to pdf and by default also produce an accompanying MIDI file. The MIDI file is an extra feature and not really the purpose of `tabr`. The MIDI file should be played back in some other program that plays MIDI files. If you want to use R to play an audio signal (and perhaps MIDI, but I'm not certain at the moment), please see the `tuneR` package.

Matt
