### ISSUE TITLE
tab is not working on MacOS

### ISSUE THREAD

**Issue by chatzis** [leonawicz/tabr#9]
The 'system()' line in tab works for Windows OS only.

For MacOS needs to be something like:
system(paste0(tabr_options()$lilypond, " --", fp$ext, " -dstrip-output-dir=#f ", fp$lp))

Also, the options would be something like
tabr_options(lilypond = "/Users/userx/bin/lilypond")

without the ".exe" at the end.

Great package BTW. Thanks for doing this. Looking forward to explore it more.

Christos

**Comment by leonawicz** [comment]
I'm sorry I overlooked this issue. I'm not sure how I missed it.

I do not have a Mac system to test on directly and have relied on other users to report back that it is working for Mac, which is what some users had previously told me. Can you let me know if this is still relevant?

At a minimum, I agree, it sounds like the options needs some cleanup. It would be good to know why it is working for some and not others. I have not had time to work on `tabr` in a while, but I will take a look soon.

Thanks :)
Matt
